### ISSUE TITLE
BBCode Tag Workarounds

### ISSUE THREAD

**Issue by Alteras1** [RpNation/bbcode#106]
Due to how the built in markdown engine processes inline and block level bbcodes, some specific tag orders aren't supported.

For example:
![image](https://github.com/RpNation/bbcode/assets/42795314/e76784ff-415f-4422-8b7b-9d08e44ec876)

likely workaround would be to just add those simple default tags (italic, bold, underline, etc.) manually ourselves to the BBob plugin.

**Comment by Alteras1** [comment]
I think this would only apply to the ones marked as inline bbcode in the markdown engine? We'd probably need to read through the source code to grab them

**Comment by kyuukestu** [comment]
Hi! I whipped up a few tests for italics, bold, underline, & strike-through and I found that discourse automatically converts these tags to their native versions when the post is baked.

Here's the code in the preview:
<img width="971" alt="image" src="https://github.com/RpNation/bbcode/assets/71295464/485b661b-2a2f-4f87-9938-b9cd60cb719b">

And here's what it turns into after being baked:
<img width="550" alt="image" src="https://github.com/RpNation/bbcode/assets/71295464/4337d513-b910-49de-ae5b-cec9d349b288">
