### ISSUE TITLE
Spoiler Tag Fix

### ISSUE THREAD

**Issue by kyuukestu** [RpNation/bbcode#123]
Spoiler Tag content & Preview are displayed improperly.

![image](https://github.com/RpNation/bbcode/assets/71295464/6f3c1013-b84f-4677-90ff-188c399debde)

![image](https://github.com/RpNation/bbcode/assets/71295464/850fe4bc-d5ad-49c0-abac-527f7a4341dc)

**Comment by Alteras1** [comment]
This seems to be a byproduct of how bbob parses. It run top down and interprets tags the same way as html. So for any bbcode with a nested div, it's trying to run the [div] bbcode on it, which modifies the class name. The only way around it seems to be to force a check into the div node creation.
