### ISSUE TITLE
Quotes Broke

### ISSUE THREAD

**Issue by Mondrethos** [RpNation/bbcode#131]
![image](https://github.com/user-attachments/assets/294e7155-432b-426e-a87b-9c11b85204cd)

**Comment by Alteras1** [comment]
Let's figure out what is the built in discourse markdown for quotes and see if we can massage it to fit

**Comment by Alteras1** [comment]
https://github.com/discourse/discourse/blob/f169985fce49512114343cb84c7b9ed2eef5d235/app/assets/javascripts/discourse-markdown-it/src/features/quotes.js

**Comment by Mondrethos** [comment]
> Let's figure out what is the built in discourse markdown for quotes and see if we can massage it to fit

Any idea what is wrong?
