### ISSUE TITLE
Accordion - Alignment Options Fail when not using equals or pipe

### ISSUE THREAD

**Issue by MShultz** [RpNation/bbcode#134]
The alignment options on the accordion tag fail whenever you aren't using an `=` or `|`. See the following test cases that fail. For each of these test cases, the accordion fails to load and you are unable to submit your post with the errored BBCode.  [See Regression Testing here.](https://t.rpnation.com/t/the-regression-dump/162/2?u=faithwynters)

**Additional Notes:**
There are some cases where these alignment options do work. As mentioned above, utilizing the `=` and/or `|` syntax is successful. Additionally, if you include the width option, the slides render as expected; I suspect it's something to do with the `=`. For example, this following code DOES successfully render (Test Case, AC-010)
```
[accordion bcenter fright width="75%"]
       [slide=Slide]Content for the slide with multiple options.[/slide]
     [/accordion]
```

See the following test cases that fail. For each of these test cases, the accordion fails to load and you are unable to submit your post with the errored BBCode. 

> ### 5. **Test ID:** AC-005
> **Title:** Accordion with Bright Alignment  
>  **Code:**
>      
>    ```
>   [accordion bright]
>        [slide=Slide]Content aligned to the right.[/slide]
>      [/accordion]
> ```
> 
> **Expected Result:** The accordion should be aligned to the right side of the page.
> 
> ### 6. **Test ID:** AC-006
> **Title:** Accordion with Bcenter Alignment  
>  **Code:**
> ```
>      [accordion bcenter]
>        [slide=Slide]Content aligned to the center.[/slide]
>      [/accordion]
> ```
> **Expected Result:** The accordion should be centered on the page.
> 
> ### 7. **Test ID:** AC-007
> **Title:** Accordion with Bleft Alignment  
>  **Code:**
> ```
>      [accordion bleft]
>        [slide=Slide]Content aligned to the left.[/slide]
>      [/accordion]
> ```
> **Expected Result:** The accordion should be aligned to the left side of the page.
> 
> ### 8. **Test ID:** AC-008
> **Title:** Accordion with Fright Floating Alignment  
>  **Code:**
> ```
>      [accordion fright]
>        [slide=Slide]Floating content to the right.[/slide]
>      [/accordion]
> ```
> **Expected Result:** The accordion should float to the right side of the page.
> 
> ### 9. **Test ID:** AC-009
> **Title:** Accordion with Fleft Floating Alignment  
>  **Code:**
> ```
>      [accordion fleft]
>        [slide=Slide]Floating content to the left.[/slide]
>      [/accordion]
> ```
> **Expected Result:** The accordion should float to the left side of the page.
>

**Comment by Alteras1** [comment]
Looks like its a regression caused by #133. I can take a look

**Comment by Alteras1** [comment]
On closer inspection. looks like the root issue lies with BBob.
For some reason, it can take tags with `=` but not without it.

See their codepen
https://codepen.io/JiLiZART/full/vzMvpd

**Comment by Alteras1** [comment]
the workaround would be to add an arbitrary `=`, but this does seem like an issue that must be fixed...

<img width="1411" alt="image" src="https://github.com/user-attachments/assets/9fa983cb-2865-4dc1-8cba-e25e79fbc2c8">

**Comment by MShultz** [comment]
That could definitely work that way; I don't know if I feel strongly one way or another.
Given that users should only ever have one alignment option (right now it handles multiple gracefully, so nbd), could we do it where you are explicit to the alignment property? For example:

```
[accordion align=bright]
    [slide=Slide]Content aligned to the right.[/slide]
[/accordion]
```

```
[accordion align=fleft]
    [slide=Slide]Content aligned to the right.[/slide]
[/accordion]
```

```
[accordion align=bcenter]
    [slide=Slide]Content aligned to the right.[/slide]
[/accordion]
```
