### ISSUE TITLE
Cannot utilize Style option with pipe notation

### ISSUE THREAD

**Issue by MShultz** [RpNation/bbcode#137]
When utilizing the pipe notation `|` on a slide tag, the style attribute doesn't work. Alignment and Open options do work. 
[See test case AC-026](https://t.rpnation.com/t/faiths-bbcode-regression-topic/161/2#p-397-h-26-test-id-ac-026-failurebr-bbcode-injected-newlines-22).

For example:
```
 [accordion]
       {slide="Styled Slide"|style="color:red;"}This title should be red.{/slide}
[/accordion]
```

This code currently renders a default styled slide titled "Styled Slide|style="color:red;". It should render a slide titled "Styled Slide" with a text color of red.

**Comment by Alteras1** [comment]
I don't think we should make this a valid scenario. With curly brace and pipe notation, users are already doing `{slide=[border=1px solid red]text[/border]}`. I feel like explicit style should only apply to standard multi attribute notation.

**Comment by Alteras1** [comment]
Updated the wiki
