### ISSUE TITLE
BBCode Tag: Tables

### ISSUE THREAD

**Issue by Alteras1** [RpNation/bbcode#36]
... maybe?

Needs discussion. We can support it, or we can force everyone to just use markdown tables.

https://www.rpnation.com/bbcode/post-1171147

**Comment by Mondrethos** [comment]
@Alteras1 I thought the goal was to do 1:1 so that all old posts format. Though tables are just a pain, entirely.

**Comment by Alteras1** [comment]
we *can* support it. Honestly tables are a pain. It's the one tag I'm 100% happy with abandoning

**Comment by Mondrethos** [comment]
Markdown tables are not rendering, not even with the discourse editor wizard that makes them for you.
