### ISSUE TITLE
BBCode Tag: Google Docs (PDF)

### ISSUE THREAD

**Issue by Alteras1** [RpNation/bbcode#43]
Add `[gdoc]` bbcode tag

Note: It might be better to check how discourse handles google doc/drive embeds first

https://www.rpnation.com/bbcode/post-1171144

**Comment by Mondrethos** [comment]
Discourse natively supports embeds via link, we should drop this bbcode infavor of just the native solution. The one on xenforo is just a hacky media embed I made.

**Comment by Mondrethos** [comment]
We are migrating to the native way of handling this and having @Ghan04 convert old gdoc codes with the migration script.
