### ISSUE TITLE
Add alt tags for functionality supported by Markdown in Discourse

### ISSUE THREAD

**Issue by MShultz** [RpNation/bbcode#62]
So folks have block and inline options where they want them as well as richer backwards compatibility, we'll be adding in tags for the rudimentary text formatting options we'll be providing markdown alternatives for.

1. Bold [b]
2. Italic [i]
3. Underline [u]
4. Strikethrough [s]
5. Headers and Subheaders [h] [sh]

Update: It looks like b,i,u, and s may already be implemented. So for now we're just focusing on headers and subheaders for this one.

**Comment by kyuukestu** [comment]
Hi! I've tried to follow the example of other tags as much as possible, so for headers & sub-headers I've created simple files that apply a class to span 

e.g. Header:
```
import { toNode } from "../utils/common";
/**
 * @file Adds Header to bbcode
 * @example [h]content[/h]
 */
export const header = (node) => {
  return toNode(
    "span",
    {
      class: "post-heading",
    },
    node.content
  );
};
```
 and then created an associated style sheet based on the current Header/Sub-Header styles used on RPN.

I've noticed there's an AllowList inside the bbcode-plugin.js file and I presume I'd need to add the new classes there, but that's about all I've discovered through a bit of poking around. I don't really want to proceed without a clearer understanding of the steps taken. Would you be able to point me in the right direction? Please & Thank You!

**Comment by MShultz** [comment]
Some of the most recent PRs should be good resources for the implementation of the tags. For more straightforward tags like the header and sub-header, something like #61 shows all the files that need to be changed. The steps are usually as follows:

1. Create the tag file in the `bbcode-src/tags/` folder. This file will contain the logic needed to generate the required HTML elements for the bbcode tag. Here you will add the needed styles (either inline or classes) associated with the bbcode.
2. Create the stylesheet (where needed) for the tag in the `assets/stylesheets/common` folder. 
3. Next, import the stylesheet in the `assets/stylesheets/common/index.scss` file. This ensures the styles are available on the site when the bbcode renders.
4. Add the tag to the tags list in the `bbcode-src/preset.js` file. These are the tags that the bbcode plugin will render.
5. Add the style to the helper's allow list in `assets/javascripts/lib/discourse-markdown/bbcode-plugin.js`. If the class isn't added to this list, it will be removed during generation.
6. Update the `README.md` with for the tags you're working on.
7. You should be able to npm run build the plugin and test it out locally just to make sure you get every change. After that, you should have a new working bbcode tag! :D
