### ISSUE TITLE
Transition from [img] to Markdown Images

### ISSUE THREAD

**Issue by Mondrethos** [RpNation/bbcode#72]
We should transition from the [img] tags to native markdown image support. A good example of this is the heightrestrict bbcode. @hartleyk1

**Comment by hartleyk1** [comment]
"To add an image, add an exclamation mark (!), followed by alt text in brackets, and the path or URL to the image asset in parentheses. You can optionally add a title in quotation marks after the path or URL."

`![alt](url)`

**Comment by Alteras1** [comment]
we can change the [img] to just be a translation from bbcode to markdown syntax to help ease users in. or we can remove it entirely and force people to use markdown syntax

**Comment by Mondrethos** [comment]
> we can change the [img] to just be a translation from bbcode to markdown syntax to help ease users in. or we can remove it entirely and force people to use markdown syntax

I think the import script drops tags where it says [img]. So we might be able to just drop it entirely and make a PSA about it.

**Comment by Alteras1** [comment]
We need to confirm how exactly the data import is handling [img] tags. The live site also supports [img] tags with height and width params, so how are those being handled.

**Comment by MShultz** [comment]
The import process will handle the shift from `[img]` to the supported markdown image format. 

> The Ruby import script will strip the `[img] tags out.
> Then we'll rebake via Sidekiq to clean up images post-import as part as the full process
