### ISSUE TITLE
BBCode Tag: Code, icode, plain

### ISSUE THREAD

**Issue by Alteras1** [RpNation/bbcode#76]
add [code], [icode], [plain] bbcode tag.
- translate to markdown backtick for easy processing?
- add support to md code block and inline code to prevent processing by BBob

**Comment by Mondrethos** [comment]
I thought discourse had these basic tags in, atleast code.

**Comment by Alteras1** [comment]
it does, but in its current state, using md backticks wont work properly to escape bbcode
