### ISSUE TITLE
Fontawesome Source

### ISSUE THREAD

**Issue by Mondrethos** [RpNation/bbcode#78]
@Alteras1,

On the live site, I believe we include the Fontawesome CDN at the top of the PAGE_HEADER Template and call it a day. 

On discourse, we've been trialing on T since 2020 this plugin: 

https://meta.discourse.org/t/discourse-fontawesome-pro/150871

Cons:

- Only supports 5
- Limited to Dev Support

Alternatives:

- Download the CSS Project from the website with our pro license (but I don't think we can share it with our open source project?). We could add it as a theme component (repo) like the style component but private, to provide the CSS just for that.
- We can use the CDN like we do currently on the live site.

**Comment by Alteras1** [comment]
since we plan on adding a `[fa]` tag, we can ingest the font awesome setup to be part of the plugin itself, no need for separate theme component
